services:
  mysql-db:
    image: mysql:8.0
    container_name: social_mysql
    restart: always
    environment:
      MYSQL_DATABASE: social_scheduler
      MYSQL_ROOT_PASSWORD: Rishabh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- REDIS STACK (Server + Official GUI Ek Sath) ---
  redis-stack:
    image: redis/redis-stack:latest
    container_name: social_redis_stack
    restart: always
    ports:
      - "6379:6379"   # Ye aapke Node.js backend ke liye (Redis Server)
      - "8001:8001"   # Ye aapke browser ke liye (RedisInsight GUI)
    volumes:
      - redis_data:/data  # Taki down karne par Redis ka data delete na ho

volumes:
  mysql_data:
  redis_data:     # Ye add karna zaroori hai